/* PostgreSQL schema of database
*/

CREATE TABLE "game_version" (
  "game_version_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_version_name" varchar,
  "game_version_language" varchar
);

CREATE TABLE "property" (
  "property_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_version_id" integer,
  "property_name" varchar,
  "property_type" varchar,
  "city" varchar,
  "board_side" integer,
  "color" varchar,
  "house_cost" integer,
  "price" integer,
  "mortgage_value" integer,
  "unmortgage_cost" integer,
  "rent_basic" integer,
  "rent_one_house" integer,
  "rent_one_houses" integer,
  "rent_three_houses" integer,
  "rent_four_houses" integer,
  "rent_hotel" integer,
  "rent_multiplier_one_owned" integer,
  "rent_multiplier_two_owned" integer,
  "rent_two_owned" integer,
  "rent_three_owned" integer,
  "rent_four_owned" integer
);

CREATE TABLE "action_type" (
  "action_type_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "action_type_name" varchar,
  "exchange_type" varchar
);

CREATE TABLE "players" (
  "player_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "player_name" varchar,
  "player_piece" varchar,
  "player_order" integer
);

CREATE TABLE "special_counter" (
  "special_counter_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "counter_time" timestamp,
  "turn" integer,
  "player_id" integer,
  "jail_counter" integer,
  "free_parking_counter" integer,
  "income_tax_counter" integer,
  "luxury_tax_counter" integer,
  "land_on_start_counter" integer,
  "chance_counter" integer,
  "community_chest_counter" integer
);

CREATE TABLE "property_ownership" (
  "property_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_player_id" integer,
  "mortgaged" boolean,
  "houses" integer,
  "hotels" integer,
  "number_owned" integer
);

CREATE TABLE "net_worth" (
  "net_worth_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "net_worth_time" timestamp,
  "turn" integer,
  "player_id" integer,
  "cash_balance" integer,
  "net_property_value" integer,
  "improvement_value" integer,
  "gross_property_value" integer,
  "net_worth" integer
);

CREATE TABLE "transactions" (
  "transaction_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_time" timestamp,
  "turn" integer,
  "party_player_id" integer,
  "counterparty_player_id" integer,
  "action_type_id" integer,
  "property_id" integer,
  "transaction_value" integer
);

ALTER TABLE "property" ADD FOREIGN KEY ("game_version_id") REFERENCES "game_version" ("game_version_id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("property_id") REFERENCES "property" ("property_id");

ALTER TABLE "property" ADD FOREIGN KEY ("property_id") REFERENCES "property_ownership" ("property_id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("action_type_id") REFERENCES "action_type" ("action_type_id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("party_player_id") REFERENCES "players" ("player_id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("counterparty_player_id") REFERENCES "players" ("player_id");

ALTER TABLE "property_ownership" ADD FOREIGN KEY ("owner_player_id") REFERENCES "players" ("player_id");

ALTER TABLE "net_worth" ADD FOREIGN KEY ("player_id") REFERENCES "players" ("player_id");

ALTER TABLE "special_counter" ADD FOREIGN KEY ("player_id") REFERENCES "players" ("player_id");
